name: CI Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Используем 4-ю версию (исправляет Warning про Node.js 20)
      - name: Checkout code
        uses: actions/checkout@v4

      # Устанавливаем Node.js (версия 24 — актуальная)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      # Устанавливаем зависимости
      - name: Install dependencies
        run: npm install

      # Запускаем линтинг
      - name: Run lint
        run: npm run lint

      # Запускаем тесты
      - name: Run tests
        run: npm test