name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Клонирование
        uses: actions/checkout@v3

      - name: Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Установка зависимостей
        run: npm install

      - name: Линтер
        run: npm run lint

      - name: Тесты
        run: npm test

      - name: Сборка
        run: |
          mkdir dist
          cp index.html dist/
          cp style.css dist/
          cp script.js dist/

      - name: Деплой
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist