name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

permissions:
  contents: write # Это нужно для деплоя

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npx eslint .

      - name: Run tests
        run: npx jest

      # ФИНАЛЬНЫЙ ЭТАП: Деплой на GitHub Pages
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # Публикуем всё содержимое корня